import "react-lazy-load-image-component/src/effects/blur.css";
import "tippy.js/animations/perspective-extreme.css";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css";
import "./index.scss";
import "./grid.css";
import "./main.scss";
import "./style.scss";
import "./responsive.scss";
document.cookie = "SameSite=None";